version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=msaqr
      - POSTGRES_PASSWORD=dockerdb123
      - POSTGRES_DB=dealDb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/dealDb
      - spring.datasource.username=msaqr
      - spring.datasource.password=dockerdb123

volumes:
  postgres-data:
